# Generated by Django 3.2.7 on 2021-11-05 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendanaan', '0002_umkm_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umkm',
            name='status',
        ),
    ]
