# Generated by Django 3.2.7 on 2021-11-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namadepan', models.CharField(default='', max_length=30, null=True)),
                ('namabelakang', models.CharField(default='', max_length=30, null=True)),
                ('deskripsibisnis', models.TextField(default='', null=True)),
                ('deskripsisumber', models.TextField(default='', null=True)),
                ('sid', models.IntegerField(default='', null=True)),
                ('noktp', models.IntegerField(default='', null=True)),
                ('namabank', models.CharField(default='', max_length=50, null=True)),
                ('norekening', models.IntegerField(null=True)),
                ('namapemilik', models.CharField(default='', max_length=50, null=True)),
                ('namauser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namauser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
