# Generated by Django 3.2.7 on 2021-10-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namadepan', models.CharField(max_length=30)),
                ('namabelakang', models.CharField(max_length=30)),
                ('tempatlahir', models.CharField(max_length=30)),
                ('tanggallahir', models.DateField()),
                ('latarbelakang', models.TextField()),
                ('notelpon', models.IntegerField()),
                ('norumah', models.IntegerField()),
                ('alamatktp', models.TextField()),
                ('provinsi', models.CharField(max_length=30)),
                ('kotakabu', models.CharField(max_length=30)),
                ('kecamatan', models.CharField(max_length=30)),
                ('kelurahan', models.CharField(max_length=30)),
                ('rt', models.IntegerField()),
                ('rw', models.IntegerField()),
                ('alamatskrg', models.TextField()),
                ('provinsi2', models.CharField(max_length=30)),
                ('kotakabu2', models.CharField(max_length=30)),
                ('kecamatan2', models.CharField(max_length=30)),
                ('kelurahan2', models.CharField(max_length=30)),
                ('rt2', models.IntegerField()),
                ('rw2', models.IntegerField()),
                ('deskripsibisnis', models.TextField()),
                ('deskripsisumber', models.TextField()),
                ('sid', models.IntegerField()),
                ('noktp', models.IntegerField()),
                ('fotoktp', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('fotoselfie', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('namabank', models.CharField(max_length=50)),
                ('norekening', models.IntegerField()),
                ('namapemilik', models.CharField(max_length=50)),
                ('namaibu', models.CharField(max_length=50)),
                ('namaahliwaris', models.CharField(max_length=50)),
                ('ubahliwaris', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='DataDiri',
        ),
        migrations.DeleteModel(
            name='Dokumen',
        ),
        migrations.DeleteModel(
            name='Pekerjaan',
        ),
    ]
