# Generated by Django 3.2.7 on 2021-11-04 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editprofil',
            name='fotoktp',
        ),
        migrations.RemoveField(
            model_name='editprofil',
            name='fotoprofil',
        ),
        migrations.AlterField(
            model_name='editprofil',
            name='namauser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namauser', to=settings.AUTH_USER_MODEL),
        ),
    ]
