# Generated by Django 3.2.7 on 2021-10-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoprofil', models.ImageField(blank=True, default='', null=True, upload_to='documents/%Y/%m/%d')),
                ('namadepan', models.CharField(default='', max_length=30, null=True)),
                ('namabelakang', models.CharField(default='', max_length=30, null=True)),
                ('deskripsibisnis', models.TextField(default='', null=True)),
                ('deskripsisumber', models.TextField(default='', null=True)),
                ('sid', models.IntegerField(default='', null=True)),
                ('noktp', models.IntegerField(default='', null=True)),
                ('fotoktp', models.ImageField(default='Foto KTP', null=True, upload_to='documents/%Y/%m/%d')),
                ('fotoselfie', models.ImageField(default='Foto Selfie', null=True, upload_to='documents/%Y/%m/%d')),
                ('namabank', models.CharField(default='', max_length=50, null=True)),
                ('norekening', models.IntegerField(default='', null=True)),
                ('namapemilik', models.CharField(default='', max_length=50, null=True)),
                ('namaibu', models.CharField(default='', max_length=50, null=True)),
                ('namaahliwaris', models.CharField(default='', max_length=50, null=True)),
                ('ubahliwaris', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='DataDiri',
        ),
        migrations.DeleteModel(
            name='Dokumen',
        ),
        migrations.DeleteModel(
            name='Pekerjaan',
        ),
    ]
