# Generated by Django 3.2.7 on 2021-10-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20211024_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='editprofil',
            name='fotoprofil',
            field=models.FileField(default='Foto Profil', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='editprofil',
            name='fotoktp',
            field=models.FileField(default='Foto KTP', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='editprofil',
            name='fotoselfie',
            field=models.FileField(default='Foto Selfie', upload_to='documents/%Y/%m/%d'),
        ),
    ]
