# Generated by Django 3.2.7 on 2021-10-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_auto_20211027_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofil',
            name='norekening',
            field=models.IntegerField(null=True),
        ),
    ]
